/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalitikRouteImport } from './routes/analitik'
import { Route as KonularRouteImport } from './routes/konular'
import { Route as ProgramRouteImport } from './routes/program'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalitikRoute = AnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => rootRouteImport,
} as any)
const KonularRoute = KonularRouteImport.update({
  id: '/konular',
  path: '/konular',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/konular': typeof KonularRoute
  '/program': typeof ProgramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/konular': typeof KonularRoute
  '/program': typeof ProgramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analitik': typeof AnalitikRoute
  '/konular': typeof KonularRoute
  '/program': typeof ProgramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analitik' | '/konular' | '/program'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analitik' | '/konular' | '/program'
  id: '__root__' | '/' | '/analitik' | '/konular' | '/program'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalitikRoute: typeof AnalitikRoute
  KonularRoute: typeof KonularRoute
  ProgramRoute: typeof ProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analitik': {
      id: '/analitik'
      path: '/analitik'
      fullPath: '/analitik'
      preLoaderRoute: typeof AnalitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konular': {
      id: '/konular'
      path: '/konular'
      fullPath: '/konular'
      preLoaderRoute: typeof KonularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalitikRoute: AnalitikRoute,
  KonularRoute: KonularRoute,
  ProgramRoute: ProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
